// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/hdq"
)

const _ = true
//line tutorial/01-Links/links.gop:6:1
func links(r interface{}) []string {
//line tutorial/01-Links/links.gop:7:1
	doc := hdq.Source(r)
//line tutorial/01-Links/links.gop:8:1
	return func() (_gop_ret []string) {
//line tutorial/01-Links/links.gop:8:1
		doc.Any().A().Gop_Enum(func(a hdq.NodeSet) {
//line tutorial/01-Links/links.gop:8:1
			if
//line tutorial/01-Links/links.gop:8:1
			link := func() (_gop_ret string) {
//line tutorial/01-Links/links.gop:8:1
				var _gop_err error
//line tutorial/01-Links/links.gop:8:1
				_gop_ret, _gop_err = a.Href__0()
//line tutorial/01-Links/links.gop:8:1
				if _gop_err != nil {
//line tutorial/01-Links/links.gop:8:1
					return ""
				}
//line tutorial/01-Links/links.gop:8:1
				return
			}(); link != "" {
//line tutorial/01-Links/links.gop:8:1
				_gop_ret = append(_gop_ret, link)
			}
		})
//line tutorial/01-Links/links.gop:8:1
		return
	}()
}
//line tutorial/01-Links/links.gop:11
func main() {
	for
//line tutorial/01-Links/links.gop:11:1
	_, link := range links("zip://../02-GithubRepos/data.zip#index.htm") {
//line tutorial/01-Links/links.gop:12:1
		fmt.Println(link)
	}
}
