// Code generated by gop (Go+); DO NOT EDIT.

package torch

import (
	"github.com/goplus/hdq"
	"github.com/goplus/hdq/fetcher"
	"github.com/qiniu/x/errors"
	"strings"
)

const GopPackage = "github.com/goplus/hdq"
const _ = true
const spaces = " \t\r\n¶"

type Result struct {
	Name string `json:"name"`
	Doc  string `json:"doc"`
	Sig  string `json:"sig"`
}
//line fetcher/torch/pysig_torch.gop:37:1
// New creates a new Result from a html document.
func New(doc hdq.NodeSet) Result {
//line fetcher/torch/pysig_torch.gop:39:1
	fn := doc.Any().Dl().Class("py function")
//line fetcher/torch/pysig_torch.gop:40:1
	decl := func() (_gop_ret string) {
//line fetcher/torch/pysig_torch.gop:40:1
		var _gop_err error
//line fetcher/torch/pysig_torch.gop:40:1
		_gop_ret, _gop_err = fn.FirstElementChild().Dt().Text__0()
//line fetcher/torch/pysig_torch.gop:40:1
		if _gop_err != nil {
//line fetcher/torch/pysig_torch.gop:40:1
			_gop_err = errors.NewFrame(_gop_err, "fn.firstElementChild.dt.text", "fetcher/torch/pysig_torch.gop", 40, "torch.New")
//line fetcher/torch/pysig_torch.gop:40:1
			panic(_gop_err)
		}
//line fetcher/torch/pysig_torch.gop:40:1
		return
	}()
//line fetcher/torch/pysig_torch.gop:41:1
	pos := strings.IndexByte(decl, '(')
//line fetcher/torch/pysig_torch.gop:42:1
	if pos > 0 {
//line fetcher/torch/pysig_torch.gop:43:1
		name := strings.TrimPrefix(decl[:pos], "torch.")
//line fetcher/torch/pysig_torch.gop:44:1
		sig := decl[pos:]
//line fetcher/torch/pysig_torch.gop:45:1
		return Result{strings.TrimSpace(name), "", strings.TrimRight(sig, spaces)}
	}
//line fetcher/torch/pysig_torch.gop:47:1
	return Result{"", "", "<NULL>"}
}
//line fetcher/torch/pysig_torch.gop:50:1
// Input returns the input URL for the given name.
func Input(name string) interface{} {
//line fetcher/torch/pysig_torch.gop:52:1
	return "https://pytorch.org/docs/stable/generated/torch." + name + ".html"
}
//line fetcher/torch/pysig_torch.gop:55:1
func init() {
//line fetcher/torch/pysig_torch.gop:56:1
	fetcher.Register("torch", New, Input)
}
